apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-multisource-inverted
  labels:
    argocd-team: a
spec:
  destination:
    namespace: nginx1
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 22.3.3
  - repoURL: https://github.com/aveuiller/argocd-tests.git
    targetRevision: main
    path: /resources
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
